name = "fedora-42-workstation"
description = "Fedora 42 Workstation"
version = "0.4.0"
distro = "fedora-42"

# --- GROUPS (Environments) ---
[[groups]]
name = "c-development"
[[groups]]
name = "headless-management"
[[groups]]
name = "development-tools"
[[groups]]
name = "container-management"
[[groups]]
name = "system-tools"
[[groups]]
name = "admin-tools"

[[packages]]
name = "kernel"
version = "*"
[[packages]]
name = "kernel-devel"
version = "*"
[[packages]]
name = "kernel-headers"
version = "*"
[[packages]]
name = "kernel-modules"
version = "*"
[[packages]]
name = "kernel-modules-core"
version = "*"
[[packages]]
name = "kernel-modules-extra"
version = "*"
[[packages]]
name = "kernel-tools"
version = "*"
[[packages]]
name = "kernel-tools-libs"
version = "*"

[[packages]]
name = "anaconda"
version = "*"
[[packages]]
name = "anaconda-gui"
version = "*"
[[packages]]
name = "anaconda-dracut"
version = "*"
[[packages]]
name = "dracut-live"
version = "*"
[[packages]]
name = "dracut-network"
version = "*"
[[packages]]
name = "dracut"
version = "*"
[[packages]]
name = "ipxe-roms"
version = "*"
[[packages]]
name = "ipxe-roms-qemu"
version = "*"

[[packages]]
name = "bash"
version = "*"
[[packages]]
name = "coreutils"
version = "*"
[[packages]]
name = "bind-utils"
version = "*"

[[packages]]
name = "erofs-utils"
version = "*"
[[packages]]
name = "nbd"
version = "*"
[[packages]]
name = "cifs-utils"
version = "*"
[[packages]]
name = "bluez"
version = "*"

# Vagrant & Virtualization Utilities
[[packages]]
name = "nfs-utils"
version = "*"
[[packages]]
name = "rsync"
version = "*"
[[packages]]
name = "tar"
version = "*"
[[packages]]
name = "python3-libdnf5"
version = "*"
[[packages]]
name = "fedora-workstation-repositories"
version = "*"

# # Ansible & Collections
[[packages]]
name = "ansible"
version = "*"
[[packages]]
name = "ansible-collection-ansible-posix"
version = "*"
[[packages]]
name = "ansible-collection-community-docker"
version = "*"
[[packages]]
name = "ansible-collection-community-library_inventory_filtering_v1"
version = "*"
[[packages]]
name = "ansible-collection-community-libvirt"
version = "*"
[[packages]]
name = "ansible-collection-community-postgresql"
version = "*"
[[packages]]
name = "ansible-collection-containers-podman"
version = "*"
[[packages]]
name = "linux-system-roles"
version = "*"

[[packages]]
name = "libva-intel-media-driver"
version = "*"

[[packages]]
name = "NetworkManager"
version = "*"
[[packages]]
name = "NetworkManager-config-connectivity-fedora"
version = "*"
[[packages]]
name = "firewalld"
version = "*"
[[packages]]
name = "chrony"
version = "*"

# Containers
[[packages]]
name = "docker-ce"
version = "*"
[[packages]]
name = "docker-ce-cli"
version = "*"
[[packages]]
name = "docker-compose-plugin"
version = "*"
[[packages]]
name = "docker-buildx-plugin"
version = "*"
[[packages]]
name = "podman"
version = "*"
[[packages]]
name = "podman-compose"
version = "*"
[[packages]]
name = "libvirt-daemon"
version = "*"
[[packages]]
name = "qemu-kvm"
version = "*"
[[packages]]
name = "qemu-device-display-virtio-gpu"
version = "*"
[[packages]]
name = "qemu-device-display-virtio-vga"
version = "*"
[[packages]]
name = "qemu-guest-agent"
version = "*"
[[packages]]
name = "vagrant-registration"
version = "*"
[[packages]]
name = "vagrant-libvirt"
version = "*"

[[packages]]
name = "gnome-shell"
version = "*"
[[packages]]
name = "gnome-control-center"
version = "*"
[[packages]]
name = "gnome-desktop4"
version = "*"
[[packages]]
name = "gnome-initial-setup"
version = "*"
[[packages]]
name = "gnome-session"
version = "*"
[[packages]]
name = "gnome-session-wayland-session"
version = "*"
[[packages]]
name = "gnome-software"
version = "*"
[[packages]]
name = "gnome-software-fedora-langpacks"
version = "*"
[[packages]]
name = "gnome-software-rpm-ostree"
version = "*"
[[packages]]
name = "gnome-text-editor"
version = "*"
[[packages]]
name = "gdm"
version = "*"

[[packages]]
name = "code"
version = "*"
[[packages]]
name = "google-chrome-stable"
version = "*"
[[packages]]
name = "micro"
version = "*"

[[packages]]
name = "zsh"
version = "*"
[[packages]]
name = "zoxide"
version = "*"
[[packages]]
name = "ranger"
version = "*"
[[packages]]
name = "kitty"
version = "*"
[[packages]]
name = "htop"
version = "*"
[[packages]]
name = "lnav"
version = "*"
[[packages]]
name = "lm_sensors-devel"
version = "*"

[customizations.kernel]
append = "rhgb quiet selinux=0"

[customizations.services]
enabled = ["custom-first-boot", "sshd", "NetworkManager", "firewalld", "gdm", "chronyd"]

[customizations.firewall.services]
enabled = ["ssh", "ntp", "samba-client", "rsyncd"]

[customizations.timezone]
timezone = "America/New_York"
ntpservers = ["2.fedora.pool.ntp.org"]

[customizations.locale]
languages = ["en_US.UTF-8"]
keyboard = "us"

[[customizations.user]]
name = "b08x"
description = "b08x Workstation User"
password = "$6$J5OB1cn6FxTmoSgY$S2xD15eZitgl100OGyLi1VtYMiyiIvLzd3WF2MeU.MiCGvqVZT3/zq5LZsRJD2m/P3cVg3XnX.bYqXKQYHYNF."
groups = ["wheel", "docker", "libvirt", "qemu", "audio", "video", "input", "render"]
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHHmjWwIbKqZ0TV+BxmHPVD3CV3eFdduB3JhYj2BzTAt rwpannick@gmail.com"

[[customizations.files]]
path = "/etc/sudoers.d/99-user"
data = "b08x ALL=(ALL) NOPASSWD: ALL"
mode = "0440"

[[customizations.files]]
path = "/etc/dnf/dnf.conf"
mode = "0755"
data = """
# see `man dnf.conf` for defaults and possible options

[main]
fastestmirror=1
max_parallel_downloads=10
clean_requirements_on_remove=True
"""

[[customizations.files]]
path = "/usr/local/sbin/custom-first-boot"
mode = "0774"
data = """
#!/usr/bin/ansible-playbook -i localhost

- name: Install Intel oneAPI MKL
  hosts: localhost
  connection: local

  tasks:
    - name: Import Intel oneAPI GPG Key
      rpm_key:
        state: present
        key: https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        validate_certs: true

    - name: Add Intel openAPI Repository
      yum_repository:
        name: oneAPI
        description: "Intel® oneAPI repository"
        baseurl: https://yum.repos.intel.com/oneapi
        enabled: true
        gpgcheck: true
        gpgkey: https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB

    - name: Update Package Cache
      dnf:
        update_cache: true

    - name: Install Intel oneAPI MKL
      dnf:
        name: intel-oneapi-mkl-devel
        state: present

    - name: Create oneAPI Environment Profile Script
      copy:
        dest: /etc/profile.d/intel-oneapi.sh
        content: |
            #!/bin/bash
            # Initialize Intel oneAPI environment variables on login
            if [ -f /opt/intel/oneapi/setvars.sh ]; then
                source /opt/intel/oneapi/setvars.sh --force > /dev/null 2>&1
            fi
        mode: '0755'
        owner: root
        group: root

    - name: Set repo priorities
      shell: |
        dnf config-manager setopt fedora.priority=0 updates.priority=0 \
        rpmfusion-free.priority=100 \
        rpmfusion-nonfree.priority=100 \
        rpmfusion-free-updates.priority=100 \
        rpmfusion-nonfree-updates.priority=100 \
        rpmfusion-nonfree-nvidia-driver.priority=100

    - name: Set Graphical Target
      shell: systemctl set-default graphical.target
"""

[[customizations.files]]
path = "/etc/systemd/system/custom-first-boot.service"
data = """
[Unit]
ConditionPathExists=/usr/local/sbin/custom-first-boot
Wants=network-online.target
After=network-online.target
After=osbuild-first-boot.service

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/custom-first-boot
ExecStartPost=mv /usr/local/sbin/custom-first-boot /usr/local/sbin/custom-first-boot-done

[Install]
WantedBy=multi-user.target
"""

[[customizations.repositories]]
id = "code"
name = "Visual Studio Code"
baseurls = [ "https://packages.microsoft.com/yumrepos/vscode" ]
gpgcheck = true
gpgkeys = [ "https://packages.microsoft.com/keys/microsoft.asc" ]
enabled = true

[[customizations.repositories]]
id = "docker-ce-stable"
name = "Docker CE Stable - x86_64"
baseurls = [ "https://download.docker.com/linux/fedora/42/x86_64/stable" ]
gpgcheck = true
gpgkeys = [ "https://download.docker.com/linux/fedora/gpg" ]
enabled = true
