#SPDX-License-Identifier: MIT-0
---
# ----------------------------------------------------------------------------
# System Configuration
# ----------------------------------------------------------------------------

timezone: "America/New_York"
locale: "en_US.UTF-8"
keymap: "us"

# ----------------------------------------------------------------------------
# GRUB Bootloader Configuration
# ----------------------------------------------------------------------------

bootloader: grub

# Default kernel parameters for quiet boot with performance optimizations
kernel_parameters_default: "splash threadirqs mitigations=off"

# Additional kernel parameters
kernel_parameters: "ipv6.disable=1 net.ifnames=0"

# GRUB visual configuration
grub_background: "/usr/share/backgrounds/syncopated/syncopated016.png"
grub_enable_os_prober: false
