[all:vars]
ansible_user="{{lookup('env', 'user')}}"
ansible_connection=ssh

[workstation:children]
dev
builder

[server:children]
headless

[dev]
gir ansible_connection=local

[builder]
tinybot

[headless]
ninjabot
