#SPDX-License-Identifier: MIT-0
---
# handlers file for base role

- name: Update DNF cache
  ansible.builtin.dnf:
    update_cache: true
  listen: "Update DNF cache"

- name: Generate locales
  ansible.builtin.command: locale-gen
  listen: "Generate locales"

- name: Update hwclock
  ansible.builtin.command: hwclock --systohc
  listen: "Update hwclock"

- name: Rebuild grub
  ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: bootloader == "grub"
  listen: "Rebuild grub"

- name: Daemon reload
  ansible.builtin.command: systemctl daemon-reload
  listen: "Daemon reload"

- name: Restart cpupower service
  ansible.builtin.systemd:
    name: cpupower
    state: restarted
  listen: "Restart cpupower service"