---

- name: Browser tasks
  block:
    - name: Enable Google Chrome repository
      ansible.builtin.command: dnf config-manager setopt google-chrome.enabled=1
      tags: ["google_chrome"]

    # Install workstation packages
    - name: Install Browser Packages
      block:
        - name: Install Google Chrome Stable
          ansible.builtin.dnf:
            name: "{{ pkgs_browsers }}"
            state: present
            update_cache: yes
          when:
            - ansible_distribution == "Fedora"
          tags: ["google-chrome"]

  become: true
  tags: ["packages"]