---

- name: Enable Google Chrome repository
  ansible.builtin.command: dnf config-manager setopt google-chrome.enabled=1
  tags: ["google_chrome"]


# Install workstation packages
- name: Install workstation packages
  tags: ["packages"]
  block:
    - name: Install Google Chrome Stable
      ansible.builtin.dnf:
        name: google-chrome-stable
        state: present
        update_cache: yes
      when:
        - ansible_distribution == "Fedora"
      tags: ["google_chrome"]