---
- name: Install python3-libdnf5 and fedora-workstation-repositories
  ansible.builtin.dnf:
    name: "{{ item  }}"
    state: present
  with_items:
    - python3-libdnf5
    - fedora-workstation-repositories
  tags: ["packages", "packages__repos"]

# Repository Installation Block
- name: Repository Setup
  block:
    - name: Install RPM Fusion Free repository
      ansible.builtin.dnf:
        name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: yes
      tags: ["rpmfusion"]

    - name: Install RPM Fusion Non-Free repository
      ansible.builtin.dnf:
        name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: yes
      tags: ["rpmfusion"]

    - name: Set repository priorities
      ansible.builtin.shell: |
        # dnf config-manager setopt "fedora.priority=10"
        # dnf config-manager setopt "fedora-updates.priority=10"
        # dnf config-manager setopt "fedora-cisco-openh264.priority=20"
        # dnf config-manager setopt "rpmfusion-*.priority=40"
        dnf config-manager setopt fedora.priority=0 updates.priority=0 rpmfusion-*.priority=100
      changed_when: false
      tags: ["dnf_priorities"]

  rescue:
    - name: Repository Setup Failed
      ansible.builtin.debug:
        msg: >
          Failed to set up repositories.
          Error details: {{ ansible_failed_result | default('Unknown error') }}
          This might be due to network connectivity issues or repository availability.
      tags: ["repo_setup"]

    - name: Set repository setup status
      ansible.builtin.set_fact:
        repository_setup_failed: true
      tags: ["repo_setup"]

  tags: ["repositories"]


