id = "home_TheLocehiliosan_yadm"
name = "Yet Another Dotfiles Manager (Fedora_42)"
type = "yum-baseurl"
url = "https://download.opensuse.org/repositories/home:/TheLocehiliosan:/yadm/Fedora_42/"
check_gpg = true
check_ssl = true
gpgkey_urls = ["https://download.opensuse.org/repositories/home:/TheLocehiliosan:/yadm/Fedora_42/repodata/repomd.xml.key"]