id = "cuda-fedora42-x86_64"
name = "cuda-fedora42-x86_64"
type = "yum-baseurl"
url = "https://developer.download.nvidia.com/compute/cuda/repos/fedora42/x86_64"
check_gpg = true
check_ssl = true
gpgkey_urls = ["https://developer.download.nvidia.com/compute/cuda/repos/fedora42/x86_64/D42D0685.pub"]