---

- name: Docker Setup
  hosts: ninjabot
  gather_facts: true
  become: true
  vars:
    path:
      - "{{ lookup('env','HOME') }}/.cargo/bin"
      - "{{ lookup('env','HOME') }}/.local/bin"
    docker_users:
      - b08x
    docker_storage: /mnt/local_storage/docker
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"

  roles:
    - { role: docker, tags: ["docker"] }
