---

- name: Workstation Setup
  hosts: dev
  gather_facts: true
  vars:
    path:
      - "{{ lookup('env','HOME') }}/.cargo/bin"
      - "{{ lookup('env','HOME') }}/.local/bin"
    ruby_version: "3.4.0"
    asdf_ruby_version: "3.3.8"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"
  pre_tasks:
    - name: Display ansible_distribution
      ansible.builtin.debug:
        msg: |
          The host {{ inventory_hostname }} has {{ ansible_distribution }} {{ ansible_distribution_major_version }} installed,
          which belongs to the {{ ansible_os_family }} OS family
      tags: ["always"]

  roles:
  - { role: base, tags: ["base", "repos", "common"] }
  - { role: zsh, tags: ["zsh"] }
  - { role: asdf, tags: ["asdf"] }
  - { role: video, tags: ["video"] }
  - role: podman
    tags: ["podman"]
    when: install_podman | default(true) | bool
  - role: docker
    tags: ["docker"]
    when: install_docker | default(false) | bool
  - { role: libvirt, tags: ["libvirt"] }
  - { role: workstation, tags: ["workstation"] }