---

- name: Manage IDE repositories and packages
  block:
    - name: Add Visual Studio Code repository
      ansible.builtin.yum_repository:
        name: code
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        enabled: true
        gpgcheck: true
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        mode: "0644"
      tags: ["vscode"]

    - name: Install IDE packages
      ansible.builtin.dnf:
        name: "{{ workstation_ide_packages }}"
        state: present

  become: true
  when: ansible_os_family == 'RedHat'
  tags: ["repos"]


- name: Install IDE packages
  block:
    - name: Install VSCode
      ansible.builtin.dnf:
        name: code
        state: present
      tags: ["vscode"]
  
  become: true
  tags: ["packages"]

- name: Install VS Code Extensions
  block:
    - name: Install VS Code Extensions
      ansible.builtin.command: "code --install-extension {{ item }}"
      loop: "{{ vscode_extensions }}"
  
  become: false
  tags: ["vscode"]